apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-4nxzh-3node-ssh-private-key
  namespace: cluster-4nxzh-3node
spec:
  encryptedData:
    ssh-privatekey: AgCEyJHrQKYib55Z75FKyQYennvs0ar5F1f9q6BLmkkpCXX0Qi8tYoFj7iuL6yYhCax4Y+4fCcoP3Gf9rZP/wIS522+hxzqJjYUrdKiaKHiavXKsFjuaf1noJM+pipmowB1pYsNSsptIBov4sO+GrUQQOmwHH/HoN3MDV/+Tn14ngVmbzBWpuDpqPp7wV7V94iBv2PP7bOGGvqKyK0DxaYwTCXhrObA4nOBhlcMKLqVM+UlvA/w3Y3FrONyPTuiN+P8JrbkG/Y97hQTzr13Eow+Mai8tD7ianfIwJgpSzD8mwg/a7cT9Nyo/RJx7z2GmME1xL/NbLuPoqQ3rPe3/gVHqRGmJKRBCczYcGQTJK6NYx/KVzjobuZU/2uTtAa16L3G6B9r6NmDkl7VWZVZHk5rjut7oGEXbSa+6IQJ5PjdvOcHGzpZop0BIQoyp88/qBEYnc8gryyPI6jH7QsbgHrcoFx0MjJHUOEXEwwx3RThaiUABY8kws+XafXsdJTmLaYdSzQ2JaI5vVxsrYWhjmR1G/SKESMfyZ0iK3zrR43ajv02SAAc0Xe6V2Ru6bb2V4ej4Vd/FCyhporAPjvTM/QPOh+FC75eVq5AKIM0BxW7IoG536GEow6tMGey79OEXO4isl46+ER4WLsjtVqSSJDvJ0nBDOnVoWlErmTIwyzaVZwhZ/tH57IsJqeHda/JjKW2YCs3eRCPACpPyQHBXkaAoLE5MEhmtPU02TDb4Q6V2rUyEzz31HWLa+H3re6vGq4RDSCEUv7i9+UWU+KLBoCLtiGRAPAdE2qeQ94+GYQ6hsAtHrOaGIJ8LZYDQT8dftiLhmpijXa5hwNW8hVxCrZM8P69hUS53k21/amhx5lnTSQ86HTTUOoMO3RZntzFTkqyRj7xnBU32uPrWPOFstAhMi8OFi1Cei0wfC5kjAPt+gvVolDP5kYWrMQVVBPLWNViyx5RSUnsuDoHxsqytEOIPZ0ngOLSfwN1kRjRc8C9DO4ocZFK8IN+DF3VvJisMs4EOQj4GTfndJkcAju6ScSWQK9JhBSNj6GzgcC0JXk5rtM/Kh8riGrLNq83EnwTNDI5hU1a907JurABOyJakTyTuFLeKb3cDOTDoeTCCVVl6345LLciIAobyepvGMN/w11V3V+eOslCpe3s8w/NZAYM/yriFjOFMIirfXBlwUAz+8IIiIXLlT2v6g79rcXx4FqfA6R7EFH2BJbxobvmuAg==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-4nxzh-3node-ssh-private-key
      namespace: cluster-4nxzh-3node
    type: Opaque

