apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-4nxzh-3node-vsphere-creds
  namespace: cluster-4nxzh-3node
spec:
  encryptedData:
    password: AgAwQpKTDmHcuhN618deFqsHxjKiY8KvWUmXCZoAIOvZ1JPdc4R1uxvMcQ/FbunyVppX/DlOLH1RchfQLpCWhnNkjJH10sNYNe8BrDMvoa7rSYtyZWnEjdmac47disE7WbFoa6B7REJhhW16MXukaHEIjMdP5qKdmKNs7esNi4WE6o9akueofeRfKAe9oHUNh+8b9GH44jLd6M0l6Zd9HJNgf4SST04oR38fU928/J0U7/DN66cu3fe/DbrzWjBVrOS51EKBmxyzQUxaA/oKQ+W4Sdkj4gvuM2GX1NgvW8sqrioR6UI33H0lacw6zrQKAzQVEkb7PRptm/a3I9gb9yxlHSQzaqNVc4tjhz7+PSfCk3sdwPMAqQhXuob8AnM+rCjmT/8YCbqCsiDipM+QEnxYOZLEO4HTmdnAidp9DOw4h+DYUE/l/7J7JCrdJ+W8aQ2k1rqMWWy5TiWUmMP0IEqlTCfcOSWymy+SvBRhHJpYVxb8rly9mUIsyEeNZgOBf/0y0ksf/2ma5kgU+G2AgNXaJ0n0ZeMSbUitdHFXV7SsvmNDhEh7afE2o7GIei8cxOuzQV6ErSavxBDoNW3ECTS/HeGGml36qNOMQ+OT7tTo46wkt03X61B/0TLBxpJEuH+zZ5qRe3Tb5hzhTfeMl3PFk+v9lgUsHxdM9S8fkUXIBw6y0oyInQe/woD3fsOgGsLE6rSxs1sGVyB+nD8=
    username: AgCSDcwjtnx4/ItFBmIzW98D6+dyMiu300AtzWTa/WU4Swfqi+el4A09RzNlA5N6Dbkq8mBfDvyq3TvU55i0LR3YSTUdDTDJIh36iRK98g00kzJXJZJAXMNhopkfE8ovTrlPpns1SoSabYKySkvXLLgbcfgo2ZdAZxdEjuNgeCY0K/ql6T0+2Y9YO53/34mwd09anK9IvEweHNM4yK5t9oJRAXPNyfib8GzdWDBqlYGKFAlIr2HGgTi12U8ZhodGFDU7po0LhRnAo+nTjlWlzXRIi2AJouA6PuVr6z274VnI1O7utq2jkBRh4eRczKixueYJnvg0XAhyGuq2fqxVhmuZIjRlrJG9mMXfpGuj8lmJmMR3eW7ZykVdmiSiFRSg7tSiUwEhEGVTVUvaDCbPMO8W/y/V2HJqgMzIDWUUpkl4cX0trEQDanQxwKZF3W/naipNHlmAlYygiWlJgalXoug22e23UluW0QtDwCn7MRtgDovmcFh+xn/krlqF+KzgZ7WSUtGfqRo61Nm+i5Hy6DaylYLKmJHID15I/KWyAyq+jw9Qpz2TvyyXI5j6zVOwIkM0kEj5HUfgXo7rPkDH6o5R/Fb+SRFzFLu/HsOrQJwq6vozz7P/O7+dFxmj0gyG63PeVpRktAEXAwybV/UJstdu8jrUv/WPM7LLVOt9pRkzPCfr8oz2/GfWcm31bHXAGf4DY3ZWdm60Wu3fUyzLZheD6hI61yY/i/7wwnVo
  template:
    metadata:
      creationTimestamp: null
      name: cluster-4nxzh-3node-vsphere-creds
      namespace: cluster-4nxzh-3node
    type: Opaque

