---
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: 'cluster-4nxzh-3node'
  namespace: 'cluster-4nxzh-3node'
  labels:
    cloud: 'vSphere'
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: 'default'
spec:
  baseDomain: 4nxzh.dynamic.opentlc.com
  clusterName: 'cluster-4nxzh-3node'
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  platform:
    vsphere:
      cluster: /SDDC-Datacenter/host/Cluster-1
      certificatesSecretRef:
        name: cluster-4nxzh-3node-vsphere-certs
      credentialsSecretRef:
        name: cluster-4nxzh-3node-vsphere-creds
      vCenter: portal.vc.opentlc.com
      datacenter: SDDC-Datacenter
      defaultDatastore: /SDDC-Datacenter/datastore/WorkloadDatastore
      network: 'segment-sandbox-4nxzh'
      folder: '/SDDC-Datacenter/vm/Workloads/sandbox-4nxzh'
  provisioning:
    installConfigSecretRef:
      name: cluster-4nxzh-3node-install-config
    sshPrivateKeySecretRef:
      name: cluster-4nxzh-3node-ssh-private-key
    imageSetRef:
      name: img4.13.4-x86-64-appsub
  pullSecretRef:
    name: cluster-4nxzh-3node-pull-secret
