---
apiVersion: v1
stringData:
  ssh-privatekey: |-
    -----BEGIN OPENSSH PRIVATE KEY-----
    -----END OPENSSH PRIVATE KEY-----
kind: Secret
metadata:
  name: cluster-name-ssh-private-key
  namespace: cluster-name
type: Opaque