apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-mx76p-ssh-private-key
  namespace: cluster-mx76p
spec:
  encryptedData:
    ssh-privatekey: AgCuZt4VFljn1/DOorbrYQZ0QkICettd9tmWvOC0fWHEs+BogNJGRNw9zhIiiLUviMXWUFiJMkS1f1i9WavegEVDn6XxbMhUT6mToSiSrvMBHzrpWuG25m+1tLdnGxZ7GjmaaXieJhKgE/JsC2uxTyhMJM7QWeOR8TazQJj29zQW6CHeDzQ+Yek+HMbBLv2DB+TCy4JobalArk9HEUNOmL16Ja7yRT5lEVcra28n+6CyuZSHBmZw0tLZk49pbdZD3tZ0OLUL4FgdSSzQRHtlihuOM1TEF7CDxkJWBboN9PbCDiiykjrSVKxo4O0f1FT2AL5bUsS00qMOPLBNTZ3G91QqTvUtWScigaAUcB+d/k/BzB1SaiapUbHZi0z0C53oUwobGJ1cVY8st7125kS/DTCeEvwQlwtiKFphJFTlvGA5QKWy0VhJ9FPeNynISHTEtDyU1Kzzq8qvU8ce2h7IB+DpHwdwQJ5hjpTNk/QzETk0Zs++qZCV+V8qKzUqaXfQogWwNFOXeLKv8+2USdsDczyRMMCuUR3Byu0y1t585qs6LuPTZ4fDNDabLCX1wLFJbaFJU8YBGct7+CLdU8HVe82mmZZcPNtz1S6dQYLfzexXryID4DrZpSFDzAjUi1Ua1k1f1fYE/XqKcOGF0d1ecnndERgAQ0VCYAEgQiDcYJqueHVtGasWwu6E6FgjOi2ejWI8p0lgtQaJ8Yw6vYf4uF6eRqdZvt/zUR937XKsTqI3CEPcZTe04MJD6f6FPJaOftt3x9eo/buj/kV+d2sDrpJ8dMsipiKj+iz7YSiPvA95apM8ZB3Vg4pjntWb2oZ0AJIvXw8TvSgKxGImtGnwSMP+WS5Bda+KeMFi7jl1Sq6nEvQWcnEko3+TbXNJWqwzds84r/ZaILMRrbRJkLXVix+Y9gTdaRQGNMuOxNb6egnXtYLCyx5oGejGyiu3qVdtnE6zzPpNCjIi607cEcbCQGkNVr659hgAIgZ3b4LZgTrWC7/LkEiak4YqPYP/HG1IZFXSkNJQ3lrCfArHDrFEv80L1UEXKtDTF/1pW9BaPvQ7RbVKsHhVWa/rozbu2G9Bi010JDX68ss/5Tks3pjIkQRmmM5p5aB69RNpridV0N1NWGw+0aWwrLwfWhJcCLMsEHCILVjCNHjyjZg5XeM8xBGMA8ReHAm518eTI8MjDYpbuXqilAFF2tviTsGS0EgEh1I08ZsLDfQU2eY3FjdlmQ==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-mx76p-ssh-private-key
      namespace: cluster-mx76p
    type: Opaque

