apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-mx76p-vsphere-creds
  namespace: cluster-mx76p
spec:
  encryptedData:
    password: AgC0GvEgM172Rw6rNh+5V0U9z+9qRn8d11bobdvAjOQOFGi9yKd0fj4AfNmpOxJTKYbr+Aj1w4G2BfBrg71mbD/idd9DtEHsibpD8+bQJYh8v3NziEmvDgkArTUOfIQmqg6Mt1shkofVmVFT1eCZ+mx1UNKY04KOnfpruKHfPfGbKp7+1jf/xekBR3f2jbwrPP0fi5pWcn4kffI+iDUBI0I0RiLAI9g7uXsXKF39IOTwjaPNzyOXvSPNhIFoQXaSdcKGt05EkTzsgLHXmW9cGjSxHGqodypGM8v4MAMT7m5r4OvQRwXZYGGrzfJvLjgAK66y7O3tg2DsXZZ82SdhvljlQFxEXQDUs6P+FoR1D/gRkhvLD9QeYz2hdRWMS6PlGb/bH69j62/7Z42esiDyEoo6oM/zBI3eBtxxltwq00sAk/UcngjOGgR0/CoH3+GdqW3iF4N4JkpssgsDZRSIaR/wNZvu8AbhwXVmtguIz8zvGSU4hKI0M/7Z/CII0E0yH5Lay7O9p7x7Pi4n9ZlbMXAINg7AMjEpSlYGYPTO2+NgoUy3kDyb5q6WlDUjxX6lrz8yhBmXULAW2kvTuMha/e5mShKm7B1Gs0bnkufXZ7UCLK9xYmRy7qpxh0nnI+kxPV+ZbMpCh9HJBYuCFrEwNepNcQxKcT1KEU6jW5DwYaYOYCfDVLy6WePLRxdUHaw0uGrhfHA7SjqWd7eEoZc=
    username: AgAdFquG0b8pe3yqSZmqTcfvOrJPKhcIU7RSC+ks6CfOVUrMnbH59brAq/8jmb8HlKtnf1g8dUYmwIDvFAJkASR53VlBPWGmiuEtcQHtgV2potLFt47UcwRloVGTADPgYrhKTOC34inulUiWdcEX3fYNXgv23bU7U4dCA9Nu8C5VjgR2thlpRRIYH/uYKlqIQthdB5Te4MruqfTEUDBNF5siQH3GSCTVYbzgimjlogCLMruwZz9XuaYhLrk4J2YzTpeJQCgCnxEwEJDk2a0AZpxq+Vb/G+N8t4NqmsIpqIEOaLopC4+wIzMULtjRHKaNyTA3MCWFnoVnkUhxqaf0vBCNo+Ov52GBC5H2B4REmFXew94mf1ZGQT70ma/HpiICJRIJrrv/j2VySil3VQR9mLnpAycZUHGBqKWXR7gXqwfEgZwBPTjcAu3suYVZlCR7HSGSIkfeTsjmHNfoA0xbF5anqnH/I9saTqNPHTj1+mLRY/+BS4CnHK+H2vdCzjIDlB/4EKMTD+RiW8cO4QzKyULx/8KQhrgVAcUM6enwhgFQy3/LtZJpWnGVkzYz3kofwa0pBy5ZMFLiWwsv/M/dJVVrhMlnb+qjXpJ01Ka2rADgk6Js+ub3cGJdZ9oLSLyDnapXmmRs0e6UD0q1tz0zzEk7vy7M/9KJonMr+7NTDAzTl9dzhCyeW9muj/mUcytdSAstCGHuigbb4xdi5EwgpdIC/yUj+s2kfV+G021Y
  template:
    metadata:
      creationTimestamp: null
      name: cluster-mx76p-vsphere-creds
      namespace: cluster-mx76p
    type: Opaque

