apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-mx76p-vsphere-creds
  namespace: cluster-mx76p
spec:
  encryptedData:
    password: AgB74n40XjKeMasU/5FQ7U8mPLAVBDBjLW7kBs9W4pzuzdkRPemw8PN4m9DaUa+Gs6Cio9zEZYM1K+LAkDfGkgs0t49xzICH/oOyK2mInKTXGQPPZj9Tc9/djWgyRDp6qye5V02TLGbsa/2zYK8iw5kGARvErGSSVwwGoocRnntwmn280fEid6EvayRObIMJgE1RdRAhBeAj9XpzQPP9PMb1+koEQ6KhhyP2JEY1/uoAKgNGVajLbkJ6vV7cXj/Fb7p7l2gqRDtqwG1C/peYU1s/es+ELRq40lBKY/a5zdtTPHZI0BxwO92L7qgIQAqHU346ah+t6ukwU4vaFeA5Gtu/JgExUFpRwWohY95Q/cey6UNeULjAdrA98mEAKUdLKik8c7agd9hnxiCBLZEAK7OLzwUHGj16zkiPWE3lBUS1wDCb1aP+I7gYAA9qqsOnviVdnvy/jEjl3+uftA4yPWv2oWRyZzjkvu8YhjyEwccj+/6kHxmiNq9rjpnWM/GhnRaoRZo1TKnXZVnmYIC3dGZHvbn8AOz0VFKg97uIoxxqwEA8h699/IoCeQYIJxQbZTJL3F2lykRcTva/E3q4bDlNjggwSspTgv9M7Brz6vuypJv7/p9JINIYEF3TxAwku4IFQ2XqJA6eDsCwbFcgSjPPId4xmYYuCMeTJyENsAyR8GoF/Solm7voNEK+s5zZmU01ICPpG1O5qzR1UK4=
    username: AgCCKumGSULMqrjT96+a3ZuAwaS565LQG6xAGiVhPwqBJTib6qgHhvUea1zG6ZI0WdmucK9PxegdECvSPL6v5Fi8zme/pD1cxawcg21/5xj4jw9gh68NnJicKZenCYrzjvJ3bnKN3JUvzupzmOfv/8wfs1gCOJSoAHFJ1Rbj9aolmYMZBzTfxufIOWKgJ8SBmgsf6pZGbKF9xwDtQbYKJ9TjsUTyUIRLzddycGx1VoLFjfRMyg1za/FkCp+rbwkzlZFmpoQ5bt94/h9K6Kt1NRxwg+qm8Jzl7JV01AFbFSMaY94PCuwtk2krSW6x3faCL4f4sU/6P779uNcFit8paKtvdxvditwZMQNr5cKVZbvEkFyJ4h3L2CbHHWB2HvpJnT/qjiMCYGKS7H9ZA2PUgLCMBLDs8x0DK6mSzbmvkUzf2aUCC2UDWFI+vRa7C9fmPycG/v8IgeRCf8TB6GJ5Ip9jXuLyGrFVngYPXCrYPljDOalKhm7LPA5YGbk3e7ou/cBlAOoSaetzloM6U/g045Y6FrscBa7pAr3zTIPNs3nivi9S+JnBCUkxK3GkcaZbhP3sMnSOKD4anGYNIDKDqEB5deWRsdZWSRPBtmLxWyC4qrFMKjZ1ZAJpF1PR7DoGozhME8Xi8YIuTv0gnFzVX3b4Qiu7vcSMKBpFO+Jqwz4Q4CKoCHU1w3MdZAt3IyyEZmoDZoMJFhVbTvmyG3eLRU9qWauVaBS+doQcrdo7
  template:
    metadata:
      creationTimestamp: null
      name: cluster-mx76p-vsphere-creds
      namespace: cluster-mx76p
    type: Opaque

