apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-mx76p-vsphere-creds
  namespace: cluster-mx76p
spec:
  encryptedData:
    password: AgCgAfyqQCh0SgMBwzWb56AWx9PAVR37HJGsPTG0n2PBgMWR3HfYj+WxSW5YZ7rKuAdEqNWsg4Li8w42OgCRyyJcS0fmgaWYxrL9k6KxKDZb0dY+uQwhIK2FrBC62JM6AvnPa0nmEPwJ07XB/a2RfMem/WjIUzc/YSc5vn6S9PEr0zNHX5nbB9MBgj3x7xTuPLQTigsw6LlVqVe3gA5A35NlnElIhzytbh/OUeWnlRR1bsj0hIiW7EWcgmwaQ2Pgo0lh8sQxS5uBZvdANyqBhPvf8AVEVAAC94UlIbY/I8To61hfKL6zVUpoQue7ci1tRAc3N/4OAhXgKQTL0F3zCT+rDnrsLhdqGp2pdwUKqW252ejs19f8emaxAfcAdYDqLVUlM45BVZ2EDcAX8kDrLTZRR+6ZmbONpcAFVXuH4o6TtLsHdc5y8FLtC4HpzqGGRsrG0Dn1/nPGeQwTnY2qxLPalB99D3An4iyMDJD9HRCJpGo9UM2PYRAWNcP4VmjDO93yFRjnoVEGG0K4PstuECmMaN736vqtHtWocu+sVptx+iMHV6CVjThfW9tN9wIrWPRMj6ZqEwGBqQ1k5bFcSdU22+V1lVYgbPqc6AlkJ3VudB6INLlx1kPSQIX2/qgaZzM9KOXr+LQ0VfKpT4xDtqnFBuXIzIsQ5uDGX8LK/8s2FoJAof7Hlzw1sHElyCrthEGD8AsPUHdVNSrKjAI=
    username: AgAdJEzs0dyY8ybsCluNUAP2cwyEITAdzpLcEX25IWIq6GnzYE0CXQ+NhhYqdnF0XJxMrJobGoIkaWbtT0+oEooQi3N0pgLz0Ch7dqmG82X8t+PVnKkMceVrnaH/BnjTslwNyYU4Xnei5vZZjC21lY1Ykh+FKJQm8nNh6lrWdmftXWqLL0/AI1bmhaN/P4y0qUJkMast08ShZnPtZEf1mxxmVLXQw94MZ/JZy7qj88rQ6BIiI76yD0qz3aH6phb1KBRmpPBaNCwQsc4HzvpeEfbP0ZLnwWgoM2JjgcEv2P0hBiCZmat1sWDQroESGt+pXVOstorQ458QmqzouZd5bbCUNCthQY4TleoUjnZJ7Y6LeyJAL72L8HwY+vqRONQik+WVZ13uBAxldtv7BxgmjgdwRg8Gz8beE7v8O4kcSbMvXbokyck8aeANIPs50ujCKVY7OvvTV/MTZ2ifg3sOkoiUCXDiJQcQY2ZkulQeYQarf2Ru18Nwb5K3hPJuHTDwISHwl5okZguES9S1SSLZFI6nnEp4BT8TbB1JVICBgrMsg38yIx4EE7Sx/0Bzse4QvslWi1QFpVhaJZ/uHHTQPzfXBlEYlzl1QD/ZigUjMgXx5cONCSdsA8slvZiTKyD01ay3+KejG4xbm+uI8KyPgSDwBalwR8ATXGnTe46aehzeeEjZES5JMLM2jLqkqjpL7v5xRkBXVVrWPGgbLtikLtvbUp06uLMMKlTi27G2
  template:
    metadata:
      creationTimestamp: null
      name: cluster-mx76p-vsphere-creds
      namespace: cluster-mx76p
    type: Opaque

