apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pull-secret
  namespace: sushi
spec:
  encryptedData:
    .dockerconfigjson: AgCtTkI3CrJ6RoSa8m1Kg1eIIIwCq3VtYAUEg+71+mSY7YNKb8xsW16l3C0Yu63HFktB7VwKvsb3popjYF8mb9zRt/SaUT6ncRNutpQy3K16X3V2RtuBLI8c7tF/CPnryXdzRBzTyAIOiqqg4E39cxikw41bRgNEW2XQAUm79glWDODoOFHLgEPJt/DM4KJPE2FcszRy/+IYr0gVbR7H5nCOXk0NI8K2C3mYJyJCtr4nuHfXo8TM6g1hz+a+q5OtrwY83+yNBzTfU1GpQaJo52GTtorYzEqYB+28asqfyyXpFkuC/sF8kDeHWDBDxJUfs3I/aLcOr7R7NtdiRBYnO5uh/nIE/nq1SQt5jUgDn2uxf/UQcj/OxqlnekwoKZyxE4RIMjfEJ9+Jk4mMNk28A1OLh6DFG+9St3k4lcxso3zq8KjeOS+gLKY4HejWH2IA+NrX/3ZR1ndgw9BQH1UDUkceE5OxdgDAc06Er5ddSh9ckgCR222x2R+w15M4hI1/4iJn9A/grxQg/85VF+sBvUWc8fL/UrX6A/Ba2MLcPmTdyNvH30W/AX+CKb6yKwD5MiNqxYi1yd/0gMlwoNh4GlmYuGcUztxrABv42fWZKQD2SwtEgVTiDyfHT+OL2F0Ak5mPeATnG3u+3ZJMgtLUcetsuRp67dRbi1idw+zsDXd9YEdf86cIOZPHoAP6mJtBl/48RdW1yhe+3TNmxAzeJmy+YZffrlWaQJtjggAWj2eF6KTyYfJtiX182qjOWqKcLRA8QHKFfKu3yAUmIbQFKRfnXix3
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pull-secret
      namespace: sushi

