---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  annotations:
    agent-install.openshift.io/install-config-overrides: '{"networking":{"networkType":"OVNKubernetes"}}'
    argocd.argoproj.io/sync-wave: '1'
  labels:
    app.kubernetes.io/instance: clusters
  name: sushi
  namespace: sushi
spec:
  clusterDeploymentRef:
    name: sushi
  imageSetRef:
    name: openshift-v4.12.15
#  manifestsConfigMapRef:
#    name: sushi
#  mirrorRegistryRef:
#    name: quay-mirror-config
  networking:
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.130.0/24
    serviceNetwork:
      - 172.30.0.0/16
  provisionRequirements:
    controlPlaneAgents: 1
  sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDH7Z7cBVHkK6atUAHj2sofWxd2PbGrIU8sss3+XYhbWDU96VdcGwv310seu5cCH72Ix/AESnlPALg2bzlMvFv7AMe9g8pSWluFCvWWMCnWyQkAy1Bkmb4f/5z6zjq/T0A1nbuhVh7dSd62yZ9aHCvxQvvYkiGB964Ih+F7oj3ssvZ4n5KFGcASayxd4GdyfcGQxrXaaTC0dth0UsN8a766eXGUBwd6SXWXkYvDoVMDNXEjdR4TsWMoSWbDxGL0mzz9P4R/J9pg8HWhf5+Eg64tMJdd8OM0PBpetQ9qhD1J49NHRwgtwMgh5NBIPsESXYxlVQ80vqv1p9GSr97tvF+F mike@virt
