---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sushi"
  labels:
    infraenvs.agent-install.openshift.io: "sushi"
  name: sushi
  namespace: sushi
spec:
  automatedCleaningMode: metadata
  rootDeviceHints:
    deviceName: /dev/vda
  bmc:
    address: redfish-virtualmedia+http://192.168.86.27:8000/redfish/v1/Systems/538c7b9e-9c16-4d20-b434-6f83c8262608
    credentialsName: bmc-secret
    disableCertificateVerification: true
  bootMACAddress: '52:54:00:22:4d:4b'
  bootMode: UEFI
  online: true
