---
apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
  namespace: open-cluster-management
  annotations:
    unsupported.agent-install.openshift.io/assisted-service-configmap: my-assisted-service-config
#    unsupported.agent-install.openshift.io/assisted-image-service-skip-verify-tls: true
spec:
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  imageStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  mirrorRegistryRef:
    name: quay-mirror-config
  osImages:
  # - openshiftVersion: "4.8"
  #   cpuArchitecture: x86_64
  #   rootFSUrl: http://quay.eformat.me/rhcos-4.8.14-x86_64-live-rootfs.x86_64.img
  #   url: http://quay.eformat.me/rhcos-4.8.14-x86_64-live.x86_64.iso
  #   version: 48.84.202110042259-0
  # - openshiftVersion: "4.9"
  #   cpuArchitecture: x86_64
  #   rootFSUrl: http://quay.eformat.me/rhcos-4.9.0-x86_64-live-rootfs.x86_64.img
  #   url: http://quay.eformat.me/rhcos-4.9.0-x86_64-live.x86_64.iso
  #   version: 49.84.202110081407-0
  # - openshiftVersion: "4.10"
  #   cpuArchitecture: x86_64
  #   rootFSUrl: http://quay.eformat.me/rhcos-4.10.3-x86_64-live-rootfs.x86_64.img
  #   url: http://quay.eformat.me/rhcos-4.10.3-x86_64-live.x86_64.iso
  #   version: 410.84.202202251620-0
  # - openshiftVersion: "4.11"
  #   version: "411.86.202211230601-0"
  #   rootFSUrl: http://quay.eformat.me/rhcos-4.11.9-x86_64-live-rootfs.x86_64.img
  #   url: http://quay.eformat.me/rhcos-4.11.9-x86_64-live.x86_64.iso
  #   cpuArchitecture: "x86_64"
  # - openshiftVersion: "4.12"
  #   version: "412.86.202302282003-0"
  #   rootFSUrl: http://quay.eformat.me/rhcos-4.12.3-x86_64-live-rootfs.x86_64.img
  #   url: http://quay.eformat.me/rhcos-4.12.3-x86_64-live.x86_64.iso
  #   cpuArchitecture: "x86_64"
  - openshiftVersion: "4.12"
    version: "412.86.202303211731-0"
    rootFSUrl: http://quay.eformat.me/rhcos-4.12.17-x86_64-live-rootfs.x86_64.img
    url: http://quay.eformat.me/rhcos-4.12.17-x86_64-live.x86_64.iso
    cpuArchitecture: "x86_64"
  # osImages:
  # - openshiftVersion: "4.8"
  #   cpuArchitecture: x86_64
  #   rootFSUrl: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.14/rhcos-4.8.14-x86_64-live-rootfs.x86_64.img
  #   url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.14/rhcos-4.8.14-x86_64-live.x86_64.iso
  #   version: 48.84.202110042259-0
  # - openshiftVersion: "4.9"
  #   cpuArchitecture: x86_64
  #   rootFSUrl: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.0/rhcos-4.9.0-x86_64-live-rootfs.x86_64.img
  #   url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.0/rhcos-4.9.0-x86_64-live.x86_64.iso
  #   version: 49.84.202110081407-0
  # - openshiftVersion: "4.10"
  #   cpuArchitecture: x86_64
  #   rootFSUrl: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.10/4.10.3/rhcos-4.10.3-x86_64-live-rootfs.x86_64.img
  #   url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.10/4.10.3/rhcos-4.10.3-x86_64-live.x86_64.iso
  #   version: 410.84.202202251620-0
  # - openshiftVersion: "4.11"
  #   version: "411.86.202211230601-0"
  #   rootFSUrl: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.11/4.11.9/rhcos-4.11.9-x86_64-live-rootfs.x86_64.img
  #   url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.11/4.11.9/rhcos-4.11.9-x86_64-live.x86_64.iso
  #   cpuArchitecture: "x86_64"
  # - openshiftVersion: "4.12"
  #   version: "412.86.202302282003-0"
  #   rootFSUrl: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.12/4.12.3/rhcos-4.12.3-x86_64-live-rootfs.x86_64.img
  #   url: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.12/4.12.3/rhcos-4.12.3-x86_64-live.x86_64.iso
  #   cpuArchitecture: "x86_64"
  - openshiftVersion: "4.13"
    version: "413.92.202306070210-0"
    rootFSUrl: http://quay.eformat.me/rhcos-4.13.17-x86_64-live-rootfs.x86_64.img
    url: http://quay.eformat.me/rhcos-4.13.0-x86_64-live.x86_64.iso
    cpuArchitecture: "x86_64"
