apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: assisted-deployment-pull-secret
  namespace: open-cluster-management
spec:
  encryptedData:
    .dockerconfigjson: AgCAPoMYEIFaabauBNESMc8Y+v5mlcpIZMh2M2utD8lOPfGpDauZyrH+NaO2yaPmC2A6P1LnR327uEi0KOwlDjhiK2JmUmdijzIE8lDH8isTzM/+vHq8BbXfj/Y9DMIU/b+xlJdAJPtSPAu6ceDsYMb3qNrt3fIhQlIgYHOkB69zdqXKaGNPL9KvrPChOVqCphCqtoObK+SLWAHpFtkPbO/RLYk6gk7UiPIkCXlJPXTjjdwXoIKgVBNQMrf04/XbCFr6TVXFYDGswPivzkZ8VT9S45l5cWATm7PYCiXNrM4WSVJZDcLuxvnd8xiZi9tHyvvxam7o9VfefLlTkbtLGtNmKWk8n+85K8BLV7M9jcxzFUqrb/t+v42DXWFTAqTxpcPHjnpV0HCNBD/11vXBa3/hrLWov8rFKMpjzXBC3AUAG/2EqBBf5jM3PYXRB6xopdG6BXLpaMLkuyYg/yDPGzKCfjDV+hnhrSSg3647CG73Uffs5qd/Rut3b0/rio9g2jv1qeNQMK+lEP+Qei8sgbQvpe6kGyEagTxvZG2nitPBzMw0n6P8i2m3j/uW0mn7cy531Tl8EfYuMy3ip1SbeXZJMkhqJ2+P7BmKbDfjWFqFFKWLCsfm0Uk1wbuGdrNwyskEL2mb/iUBEkphxUTuQtN6HBhNEtffKe0uX+1iuLRzb4L2zYiLkMMnWqMxPOqctpqV+4k1NdL/nMTtNjFhqJvvEwBPLLFpBrC1QCCRCU73+0f+qDAQC3jozvP5oB2cR4url1bzktDcLALSfvDKO5Yw+Cok
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: assisted-deployment-pull-secret
      namespace: open-cluster-management
