apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: assisted-deployment-pull-secret
  namespace: open-cluster-management
spec:
  encryptedData:
    .dockerconfigjson: AgCJcH3yZOeiomcjQ+/Vgq+NzI4qOqCvVMPr/Rlp8Lzxob4V5cYE13BcD0hQI6AwUq4F9JLNkF0b6gaxuxCro3sRh+FZ6y4aDRzqtZXz71iOTE+sIo8z82ah9nVWx2iNiawursIskXznfQ3kK43un2U1GpfAz/QqVUoFXUFGayklrvV5bdC1cebb5AJHyUKqgXT1WBnWx/oJBkFMzCgo11GC/wZr+Q9I+wFt0HkHCxHPILNZlbc7e1kbltVHM39O5VL87Lo83BzwWNcx6QTmUX3Cig560Uf8AxlIXLL1j+YPdBNeZSqZNf2fdOwek1l1CvfaKuD/5phx4ELq0gxYul73OEfv4ptVkVSI5HTCqdoPYy4lTAE5sPJjmVOq5bEU+Wt1LlYXRvusncRm2kzLtLF9Xy9sbWZoPq6VeRsEIGvqmQujDd0V81Wut8cnpwTJ28IiLFI8BrYnY5YhrlDi0QEw4U1sgCvFarzGsPmcGwFDm98actX7I9vowF8WwW0JTbHDdEC1bQrDd9XjsooS+JKx5As1ps44VYseuuDlwVkWcoahwgAhYGwJMpJTwDRneFvfwJxiJRmSr/kFstBtUeIZxDdkomUsuHObbEO6o66hm3pQ4iy/nF8iuc1mPA1gKshLaxLMqF/Dv5D2Y7Ja4qzRUke5so4QaePY2ifIoNo0q3J5r4vEqadnF/BTlhcv+o5qPHoyTCFYcGbfxJx/kBQ1JcUeYkYo5WdF4dTM6WIv2MgmPrN8kJ18UkcejaS1z44faPNw57lzbddorGOn8KgTxzxr
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: assisted-deployment-pull-secret
      namespace: open-cluster-management

