---
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: cluster-x269c-infra
  namespace: 'cluster-x269c'
spec:
  clusterDeploymentRef:
    name: 'cluster-x269c'
  labels:
    node-role.kubernetes.io/infra: ""
  name: infra
  platform:
    vsphere:
      cpus: 8
      coresPerSocket: 2
      memoryMB: 24576
      osDisk:
        diskSizeGB: 120
  replicas: 2
