---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    custom: gitops-operator-policy
  name: placement-mx76p-ztp-gitops-sno
  namespace: open-cluster-management-global-set
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: mx76p-ztp-gitops-sno, operator: In, values: ["true"]}