---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-name-pull-secret
  namespace: cluster-name
stringData:
  .dockerconfigjson: |-
    {"auths":{"cloud.openshift.com" ...}}
type: kubernetes.io/dockerconfigjson
