---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: ztp-gitops-vmc
placementBindingDefaults:
  name: ztp-gitops-vmc
policyDefaults:
  placement:
    placementName: placement-ztp-gitops-vmc
  categories:
    - CM Configuration Management
  complianceType: "musthave"
  controls: 
    - CM-2 Baseline Configuration
  consolidateManifests: false
  disabled: false
  namespace: open-cluster-management-global-set
  pruneObjectBehavior: "DeleteAll"
  remediationAction: enforce
  severity: medium
  standards:
    - NIST SP 800-53
  policyAnnotations: {"argocd.argoproj.io/compare-options": "IgnoreExtraneous"}
policies:
  - name: ztp-gitops-vmc
    manifests:
      - path: input/
        kustomizeOptions:
          enableAlphaPlugins: true
          enableHelm: true
