---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-name-install-config
  namespace: cluster-name
type: Opaque
stringData:
  install-config.yaml: |-
    apiVersion: v1
    metadata:
      name: name
    baseDomain: my.basedomain.com
    controlPlane:
      architecture: amd64
      hyperthreading: Enabled
      name: master
      replicas: 3
      platform:
        vsphere:
          cpus:  4
          coresPerSocket: 2
          memoryMB: 16384
          osDisk:
            diskSizeGB: 120
    compute:
    - hyperthreading: Enabled
      architecture: amd64
      name: worker
      replicas: 3
      platform:
        vsphere:
          cpus: 4
          coresPerSocket: 2
          memoryMB: 16384
          osDisk:
            diskSizeGB: 120
    networking:
      networkType: OVNKubernetes
      clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      machineNetwork:
      - cidr: 192.168.${IP}.0/24
      serviceNetwork:
      - 172.30.0.0/16
    platform:
      vsphere:
        vCenter: my.vcenter.com
        username: username
        password: password
        datacenter: SDDC-Datacenter
        defaultDatastore: /SDDC-Datacenter/datastore/WorkloadDatastore
        cluster: /SDDC-Datacenter/host/Cluster-1
        apiVIPs:
        - 192.168.${IP}.201
        ingressVIPs:
        - 192.168.${IP}.202
        network: segment-sandbox-name
        diskType: thin
        folder: /SDDC-Datacenter/vm/Workloads/sandbox-name
    publish: External
    pullSecret: '{"auths":{"cloud.openshift.com" ... }'
    sshKey: |-
        ssh-ed25519 AAA .. foo@com
