---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ include "vmc.fullname" . }}-install-config
  namespace: {{ include "vmc.fullname" . }}
spec:
  encryptedData:
    install-config.yaml: {{ .Values.sealedSecrets.installConfig }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ include "vmc.fullname" . }}-install-config
      namespace: {{ include "vmc.fullname" . }}
    type: Opaque
