---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ include "vmc.fullname" . }}-pull-secret
  namespace: {{ include "vmc.fullname" . }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.sealedSecrets.dockerconfigjson }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ include "vmc.fullname" . }}-pull-secret
      namespace: {{ include "vmc.fullname" . }}
    type: kubernetes.io/dockerconfigjson
