---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ include "vmc.fullname" . }}-ssh-private-key
  namespace: {{ include "vmc.fullname" . }}
spec:
  encryptedData:
    ssh-privatekey: {{ .Values.sealedSecrets.sshPrivatekey }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ include "vmc.fullname" . }}-ssh-private-key
      namespace: {{ include "vmc.fullname" . }}
    type: Opaque
