---
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: {{ include "vmc.fullname" . }}-infra
  namespace: {{ include "vmc.fullname" . }}
  labels:
    machine.openshift.io/cluster-api-machine-role: infra
    machine.openshift.io/cluster-api-machine-type: infra
spec:
  clusterDeploymentRef:
    name: {{ include "vmc.fullname" . }}
  labels:
    node-role.kubernetes.io/infra: ""
  name: infra
  platform:
    vsphere:
      cpus: 8
      coresPerSocket: 2
      memoryMB: 24576
      osDisk:
        diskSizeGB: 120
  replicas: 4
