---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: {{ include "vmc.fullname" . }}
  namespace: {{ include "vmc.fullname" . }}
spec:
  clusterName: {{ include "vmc.fullname" . }}
  clusterNamespace: {{ include "vmc.fullname" . }}
  clusterLabels:
    cloud: vSphere
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
