---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: vSphere
    name: {{ include "vmc.fullname" . }}
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: default
  name: {{ include "vmc.fullname" . }}
spec:
  hubAcceptsClient: true
