---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ include "vmc.fullname" . }}-vsphere-creds
  namespace: {{ include "vmc.fullname" . }}
spec:
  encryptedData:
    password: {{ .Values.sealedSecrets.vspherePassword }}
    username: {{ .Values.sealedSecrets.vsphereUsername }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ include "vmc.fullname" . }}-vsphere-creds
      namespace: {{ include "vmc.fullname" . }}
    type: Opaque
