apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-7xbw7-ssh-private-key
  namespace: cluster-7xbw7
spec:
  encryptedData:
    ssh-privatekey: AgBN+3j3tS01uQHTuW79Hca5lYaB3kSoM/CeXceKdjgUoIBuGJK7y1dkhj5Mwpg192+4FGUWvxx4E816BSa5WetZ+qt8cmAXD8Kq2dSUcevsZZGsatASOLc00zNMxNp8h0n+N/vo7O+sdYMjPoOmtzGgtrfFv0WfbYErmvaWPiUNdUyN4MQJlCinfnjZOdRaMaAeqqnNArK9KDJyHkZ59Ba3dOmX5NSKSWOu/zDkYkJTwIALONjXudb0qBn6kyMUiITHs6nl2QaoChVKnou/8VTNNOBIG31xkCNylkBfwf/BnSnk3F1UF+/nrCwRzFd6juAjTngUKiNvw07jB1b3xoi2HE7CkMMsnoAqXS08nzOBTU3+hnvlEoaJkV6WxrcTOOC4gh7li3wjXulxnDi2BatZiEYrg6fNr9ojxh8n1MyOKWzQdKj7eOfog/rgyYZViYCTguOWYMh1p4bVrrlPHE6vLqKujti5jLTLIDPKLnIcu8WzDOr3C05RSsFJh4yAelbjm3MVymo2GWKNwHbNyjWhnuDkA0mKP3id7OPJFYoCTozNUomZy5BWFSBV1LPKW7XK8vpzsZL2RRdx0fcq1aplz+mJyX6b1DmxaP/HmmBRxXDhaDuxLVCGvJ+wPRV6yeg5QbupSGflaDHumEMD5GHHTm/yZf9nSeiOgH0tgiZBLSVXZNZcVuO0oc3nS8/X7doSiey1vMeAnJ6m9RwSJt2JCxtCLKjV4ZrKw3RlnqWBhcRVJx/hRCRVz8XD4FuZvwSEDnUkd0e2IpMf4p8nV48Jk3dDN2ThKs/aIVJ5GyDeFjnEv89EiY1IS41fx0wn8Yybaus/h/ccmloiDAUrnJASSU4IeAhOwmJwbS0EE0BwgaY3DfrER9gPIlhfv9V1Vsv7N8pkmPbYm5iwhNaT4HnGZ+qQFjzzBhD5FOL57mVqQMNr+44xKw9gPGeKrvJXXJ0o/gb4V3ZN/dJCZLRl0c7GfbW+J5vrMuTV9qDXSWQnzbh2wXFRFE8UzDn+YL3ZRoBwzKWx6SVIMzbd+9qKHqtF9Zl7TovRVN+KTo439Q0hZawlFA1vUmOE0Ti4GJJq22ONIXOmR/d7inHjrjdhQJwcRk6JWLxqtrG1eKNgP6AId0CCOTZfK3CKbvGZ0q4caO/kKc62NAHBemnAOrwTsMcZAOmeaxu3UceN0P/AnX6q9AWP3g4cVVmupzcjgACId7ZMNyg7fBgO/UaMSiaC7w==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-7xbw7-ssh-private-key
      namespace: cluster-7xbw7
    type: Opaque

