apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-x269c-vsphere-creds
  namespace: cluster-x269c
spec:
  encryptedData:
    password: AgAm+CihLtNDtLTrqyqW6Ml0pLfLReV+vWLx1DrBrl0X30YmWGzfIvwKRHHtD94vnkFxPREdKnkkjE6O/alQLtk4FZjpvq19lJQXexXtGCZOV5+89iIhFR0vQKTwoI2jWfK5HLnG/oijDDg4nvDknNTceL76amVNZWZrVyFMRhtIPHmgbDgG2iB/Rqpal7xJ8p2K9GejebtylG1nrmkXjtApt84AEgwoc2/95e20mRTOPCKNs933EMpfm7hryMJG8KHw9E6KH4Zkeam9a4iG0Z9Hm4Lv0DCjUK/VSoByjwZ9Fstp/TyU60SUBOQgrzHYX+XY+j78T4aN6P4/5SrEFvzwTYVrIMKKP0nxpKPLdf478IffYufTBUZPAvrBWVTb1NVrMhOMLkPnSttQQV3E3FePkd+miYxtHAQHkPB0DVzDu7BJXzSKNdnNQARG2cvR2WYHy0ara/XyZ1GfgTNLI3srVxarqx+OHKKMwn8u9LsPBcgNN1AoNLyTsKExuZu8PZXyRf6kPh2wTEfB0pOffGa7Av+WfPEpUqpdBPFlC/J2qutl3XQEAObsrkxXoD6e5DVim8/MtQwPUrIr4k8+ZizqY6cSpK0YUH52HrW35z63ipqpq1OwMaZqUaJNf1lP+ZztVyXo6u6L50qsfBAZvzQAC93CLnBV6WjAvxV9LAhgbHgieRS/wBhCv6Bpx0Dyw1NuZL8RAn5dIVlEpyM=
    username: AgAs+7JLcwklO0pDGi7+sPcTo3m70cHbHF7fyViabs2x3YOw+cH1BBc6N6o3nJJwdEHLpkSQYwBoHseKaPA4PfrVUqUTyYw/mwq6c7RKTiVOPazzw3Y/YGIIRN9rVttO+P9yHL6PLah7uHPiCm6IRCZerGG9QngUfy5m5R0TjdGA33Q3jFn5JppDNgaT//cTlxneB1fHNRG3Q1oNfIV5GZfRFq4kZTXQG4flTuzzJNSrVpjuLtsv/3PwxX5pnaPHi/UjHeG3PD87mND38XSAbFnx/8v/CmQlHeVA8KfSrfwKNcsRQMwYQP5jtJJba8wvxOwTit1ssX8nf5yMUGvtc11nsTJr+2XSmtlIPuOyIbqJtjuGi9fu3C8F2XARChDHQZBHntIkDTQsnJ6YLV2wKVE76Zw3l9IsWZCZVPpNJ1XUHOWWipnZBDbCzwqh0YW0E79eXHP5Y3xVHHweu1zGS6SKX4k7KZFyR7oQ4NqSYygke+s5MYuytKYB9MmrGyBptwBWBbOD3my0602ldDfrqH3Oz/JaycsJODcxpi+UJXC1NmlAH2gJCk6K+9Q1gOtVdIqmKMsyC7sCPrvHq0axnNYvqUTRYoL7K7bLRpw6eVhh1RnwqBFQkiqF+55qYmkRU6qS3/dUkJHmsMVHGbGn+NyzvxhAJcfaTv1pa11Rjzikb1UQxiHDNRspV4M71S8mTc+56EJWgtT76NOy1ueErRSW1LVl10RZx5tFU3Ug
  template:
    metadata:
      creationTimestamp: null
      name: cluster-x269c-vsphere-creds
      namespace: cluster-x269c
    type: Opaque

